[alembic]
# A generic, single database configuration.
# path to migration scripts
script_location = alembic

# The database connection URL.
# This should be your PostgreSQL URL.
sqlalchemy.url = postgresql+psycopg2://postgres:Sree%40123@localhost:5432/interview_mvp

# Other settings...
# The following lines are usually uncommented by default.
# Leave them as is unless you have a specific reason to change them.
# script.py.mako is a Mako template file which is used to generate new migration scripts.
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =